import { createContext, useState, useContext } from 'react';
import type { ReactNode } from 'react';

type Language = 'en' | 'es';

const translations = {
  en: {
    nav: {
      products: "Impactful Products",
      methodology: "Methodology",
      experience: "Experience",
      education: "Education",
      about: "About",
      cv: "Download CV"
    },
    hero: {
      badge: "Senior Product Designer & UX Engineer",
      title1: "Product design",
      title2: "driven by engineering",
      scramble: "rigor.",
      link1: "Work",
      link2: "Methodology"
    },
    products: {
      badge: "01 — Impactful Products",
      title: "Selected Work",
      subtitle: "Projects where design architecture and code quality intersect to solve real business problems.",
      nuxio_cat: "Industrial B2B",
      nuxio_desc: "A critical dashboard for industrial emergency response. Simplified complex data streams into actionable, high-contrast UI for stressful environments.",
      electro_cat: "E-Commerce",
      electro_desc: "A high-conversion frontend built with React and Firebase. Focused on micro-interactions and a frictionless checkout process.",
      figma_cat: "AI Tooling",
      figma_desc: "Component library and strict layout prompts tailored for AI-driven design generation within the Material Design 3 ecosystem.",
      agentic_cat: "AI B2B SAAS",
      agentic_desc: "Designed a complete B2B SaaS platform for an AI from scratch, focusing on scalability, data density, and user experience.",
      lab_cat: "REACT COMPONENTS",
      lab_desc: "A curated collection of our highlights: UI components designed with millimeter precision and translated into clean React code across various projects.",
      link: "View Case Study",
      lab_link_text: "View Library"
    },
    laboratory: {
      badge: "Engineering Playground",
      title: "The Desktop Lab.",
      desc: "An exhibition of 16 high-fidelity React interactions focused on B2B SaaS desktop environments. Try the Cmd+K palette, tag input, and perspective card.",
      cmdk_search: "Search issues...",
      cmdk_placeholder: "Type a command...",
      cmdk_esc: "ESC",
      cmdk_suggestions: "Suggestions",
      cmdk_assign: "Assign to me",
      cmdk_status: "Change Status",
      status_backlog: "Backlog",
      status_todo: "Todo",
      status_in_progress: "In Progress",
      status_done: "Done",
      perspective_tilt: "TILT ME",
      kanban_item1: "UX Research",
      kanban_item2: "API Integration",
      kanban_item3: "UI Polish",
      kanban_drag: "Drag to reorder",
      tags_placeholder: "Type and press enter...",
      tags_hint: "Press Enter to add",
      otp_trigger: "Trigger Error",
      skeleton_tap: "Tap to toggle",
      search_placeholder: "Search...",
      hold_deleted: "Deleted",
      hold_delete: "Hold Delete",
      swipe_lock: "Swipe Lock",
      pwd_placeholder: "Enter password",
      deploy_btn: "Deploy",
      c1_title: "Command Palette", c1_tag: "UX Pattern",
      c2_title: "Status Picker", c2_tag: "Desktop UI",
      c3_title: "3D Perspective", c3_tag: "Mouse Physics",
      c4_title: "Kanban Reorder", c4_tag: "Workspace",
      c5_title: "Animated Tabs", c5_tag: "Layout",
      c6_title: "Hold to Delete", c6_tag: "Safety UX",
      c7_title: "Auto-Focus OTP", c7_tag: "Security",
      c8_title: "Multi-Tag Input", c8_tag: "Forms",
      c9_title: "Search Shift", c9_tag: "Nav UI",
      c10_title: "Password Strength", c10_tag: "Forms",
      c11_title: "Skeleton Morphing", c11_tag: "Loading State",
      c12_title: "Voice Visualizer", c12_tag: "AI Animation",
      c13_title: "Swipe Unlock", c13_tag: "Mobile UX",
      c14_title: "Like Reaction", c14_tag: "Feedback UI",
      c15_title: "Hardware Volume", c15_tag: "Inputs",
      c16_title: "Submit State Loading", c16_tag: "Buttons"
    },
    methodology: {
      badge: "03 — Methodology",
      title: "The Logic‑First Method",
      m1_title: "Information Architecture",
      m1_desc: "Designing structures that support software growth, not just isolated screens. Every hierarchy is intentional, every flow is validated before a pixel moves.",
      m2_title: "Technical Viability",
      m2_desc: "An engineering background eliminates rework. I design within real constraints — implementable interfaces that developers build with confidence.",
      m3_title: "Smart Prototyping",
      m3_desc: "Modern tools (React, AI) validate experiences in production-like environments before a single line of production code is written."
    },
    experience: {
      badge: "04 — Career",
      title: "Work Experience",
      exp1_period: "2024 — Present",
      exp1_company: "Independent",
      exp1_role: "Freelance Product Designer",
      exp1_desc: "Focus on AI-driven products and Conversion Rate Optimization. Collaborating with startups and established brands to ship impactful design solutions.",
      exp2_period: "2025 — 2026",
      exp2_company: "Nuxio Software",
      exp2_role: "UX Lead",
      exp2_desc: "Team leadership & critical industrial platforms. Led design strategy for complex B2B products, mentoring junior designers and establishing design systems.",
      exp3_period: "In Progress",
      exp3_company: "University National of Hurlingham",
      exp3_role: "Computer Engineering",
      exp3_desc: "Building an algorithmic foundation. Bridging the gap between design intuition and engineering precision through formal computer science education."
    },
    education: {
      badge: "05 — Education",
      title: "Education",
      cert_btn: "View Certification",
      front_title: "Frontend Development Certification",
      front_desc: "Intensive program focused on building scalable, high-performance web applications using modern React ecosystems and performance optimization techniques.",
      front_inst: "CoderHouse",
      ux_title: "UX/UI Design Certification",
      ux_desc: "Comprehensive training in user-centered design, product strategy, and design systems for complex digital interfaces.",
      ux_inst: "CoderHouse",
      eng_title: "Computer Engineering",
      eng_desc: "Building an algorithmic foundation. Bridging the gap between design intuition and engineering precision through formal computer science education.",
      eng_inst: "University National of Hurlingham",
      eng_year: "2022 - In Progress"
    },
    about: {
      badge: "06 — About",
      title: "The Designer Behind the Work",
      p1: "I link design consistency with logic. As a Senior Product Designer and former UX Lead, I approach every project with the belief that truly great design isn't just beautiful — it's functional, scalable, and technically sound.",
      p2: "My engineering background gives me a unique perspective. I don't just hand off mockups — I understand the constraints and possibilities of the code.",
      p3_start: "Beyond client work, I lead a growing design community of ",
      p3_highlight: "12,000+ professionals",
      p3_end: "."
    },
    contact: {
      badge: "Get in touch",
      title: "Let's talk about your next product.",
      desc: "Available for select freelance projects and full-time opportunities. Reach out to discuss how design and engineering rigor can accelerate your product.",
      btn: "Send Email",
      subtext: "hello@alan.design · Usually responds within 24h",
      motto: "Functional beauty, always.",
      resume: "Resume"
    },
    agentic: {
      hero_title: "Agentic OS:",
      hero_subtitle: "From 0 to 1 in the AI ecosystem",
      hero_desc: "Design of a scalable MVP and UI Kit for a B2D (Business to Developer) platform aimed at managing Artificial Intelligence Agents.",
      tag_role: "Lead Product Designer",
      tag_duration: "8 weeks",
      tag_type: "Project 0 to 1",
      tag_platform: "Web App / SaaS B2B",
      context_badge: "02 — CONTEXT",
      context_title: "The Challenge and the Solution",
      problem_tag: "THE PROBLEM",
      problem_title: "Cognitive Density vs. Efficiency",
      problem_desc: "Designing for AI engineers requires absolute precision. The challenge was to manage a massive volume of raw data (token consumption, real-time logs, latency and costs of multiple LLMs) without generating visual fatigue. Traditional technical tools often sacrifice usability for functionality, resulting in overwhelming interfaces.",
      solution_tag: "THE SOLUTION",
      solution_title: "Modular and Native Ecosystem",
      solution_desc: "We developed an MVP supported by an atomic UI Kit and a deep Dark Mode, designed to reduce glare and eye strain. We prioritize typographic contrast and hierarchy in Data Tables, allowing the engineering team to iterate and scale new functionality quickly without breaking visual coherence.",
      atomic_badge: "03 — ATOMIC DESIGN",
      atomic_title: "Scalability from the foundation",
      atomic_desc: "Modular components designed with millimeter precision.",
      atomic_b1_tag: "ATOMS / INTERACTION",
      atomic_b1_title: "Error Prevention\nand Accessibility",
      atomic_b1_desc: "In developer tools, typing speed is key. We designed Focus Rings in high-contrast cyan and error states in vibrant red to provide immediate feedback without relying on long text, complying with WCAG contrast standards in Dark Mode.",
      atomic_b2_tag: "ORGANISMS / DATA",
      atomic_b2_title: "Scannability\nin High Density",
      atomic_b2_desc: "We reduced cognitive load by eliminating vertical dividing lines and using generous padding. We implemented monospaced typography to align financial metrics and statuses with semantic indicators, allowing the user to scan complex logs in seconds.",
      atomic_b3_tag: "CONVERSION & DASHBOARD",
      atomic_b3_title: "Visual Hierarchy\nBusiness Oriented",
      atomic_b3_desc: "We isolate critical data on quick-read modular cards. For the conversion (Pricing), we inverted the visual weight: we reduced the noise of secondary features and gave typographical prominence to the price and the CTA, ensuring an upgrade flow without distractions.",
      workflow_badge: "04 — WORKFLOW",
      workflow_title: "From Figma to Storybook",
      core_badge: "05 — Core Workflows",
      core_title: "Agentic OS: The Core Experience",
      core_desc: "We visualize the complete platform, orchestrating high-density data and agent control in a unified and efficient dashboard.",
      outcomes_badge: "06 — OUTCOMES & IMPACT",
      outcomes_title: "Results and Team Validation",
      metric1_title: "Handoff acceleration",
      metric1_desc: "Reduction of time to code by automating base components.",
      metric2_title: "Visual Consistency",
      metric2_desc: "Full fidelity guarantee between the atomic design in Figma and the final implementation in Storybook.",
      testimonial_quote: "Alan has a technical insight rarely seen in UX. Their AI handoff flow saved us weeks of layout. The screens arrive ready to integrate.",
      testimonial_role: "Tech Lead Frontend",
      testimonial_company: "@ Agnetic",
      next_steps_badge: "NEXT STEPS →",
      next_steps_desc: "Building publicly and sharing technical workflow with the community — documenting the modular design process, layout tricks, and AI integration in short formats for designers and developers."
    },
    nuxio: {
      hero_title_1: "Rescue, Standardization and",
      hero_title_2: "B2B SaaS Evolution.",
      hero_desc_1: "PrintFlow Pro is a comprehensive management and logistics software for printing chains, developed internally at Nuxio.",
      hero_desc_2: "As a UX/UI Lead, I executed an emergency critical redesign to save an MVP on the verge of being rejected. By reverse engineering and creating a Design System adapted to Tailwind, we transformed an inefficient design into a premium product without discarding the frontend code in production.",
      kpi_1_value: "14",
      kpi_1_unit: "Days",
      kpi_1_label: "Critical\nRedesign",
      kpi_2_value: "100%",
      kpi_2_label: "Approval of\nthe Customer",
      kpi_3_value_1: "0",
      kpi_3_value_2: "1",
      kpi_3_label: "Design System\nCreated",
      banner_role_label: "ROLE",
      banner_role_val: "UX/UI Lead",
      banner_platform_label: "PLATFORM",
      banner_platform_val: "Web App / SaaS B2B",
      banner_stack_label: "STACK & TOOLS",
      banner_stack_val: "Figma / React",
      banner_time_label: "CRITICAL TIMELINE",
      banner_time_val: "14 Days (Rescue)",
      principles_title: "Design Principles",
      p1_title: "Zero Rewrite (Technical Synergy)",
      p1_desc: "Design thinking strictly about the limitations of the existing code and the React + Tailwind stack.",
      p2_title: "Reduced Cognitive Load",
      p2_desc: "Simplify data density for operators who use the platform 8 hours a day.",
      p3_title: "Error Prevention",
      p3_desc: "Hide destructive actions and create operational failsafe flows.",
      p4_title: "Modular Scalability",
      p4_desc: "Think in atomic components so that future screens are put together like Lego pieces.",
      ts_badge: "Project Planning",
      ts_title: "Timeline Sprints",
      ts_s1_name: "SPRINT 1",
      ts_s1_week: "WEEK 1",
      ts_s1_title: "Audit and Triage",
      ts_s1_desc: "Diagnosis & stabilization",
      ts_s2_name: "SPRINT 2",
      ts_s2_week: "WEEK 2",
      ts_s2_title: "Standardization",
      ts_s2_desc: "Tailwind without rewrite",
      ts_s3_name: "SPRINT 3",
      ts_s3_week: "WEEK 3-4",
      ts_s3_title: "Re-architecture",
      ts_s3_desc: "Pages into modals",
      ts_s4_name: "SPRINT 4",
      ts_s4_week: "WEEK 5-6",
      ts_s4_title: "Handoff & QA",
      ts_s4_desc: "Storybook documentation",
      ts_legend1: "UI Audit and Rescue",
      ts_legend2: "Standardization and MVP",
      ts_legend3: "Re-architecture of UX Flows",
      ts_legend4: "Handoff and Technical QA",
      dops_badge: "DESIGN OPS",
      dops_title: "Reverse Engineering and Atomic System",
      dops_desc: "Standardization of interactive components mapped directly to Tailwind CSS classes. We eliminated layout shifts by unifying borders at 1px and improved the accessibility of the error state following WCAG regulations, all without rewriting the code base.",
      dops_stat1_val: "48+",
      dops_stat1_label: "Components",
      dops_stat2_val: "120+",
      dops_stat2_label: "Tokens",
      dops_stat3_val: "AA",
      dops_stat3_label: "WCAG Level",
      cc_title: "Reduction of Cognitive Complexity",
      cc_desc: "We transform a heavy, error-prone workflow into a modular experience. We prioritize the retention of the user's visual context, strictly respecting the technical restriction of not rewriting the Front-end.",
      cc_step1_title: "01 / The Problem",
      cc_step1_desc: "The user lost context when being redirected to a new page to edit data. The wall of inputs caused eye strain and the exposed destructive action button was a critical risk.",
      cc_step2_title: "02 / Wireframes",
      cc_step2_desc: "We ruled out cleaning the entire page, since rewriting that code violated our 14-day deadline. We sketched an overlay-based skeleton to reuse existing components.",
      cc_step3_title: "03 / The Solution",
      cc_step3_desc: "We migrate editing to contextual modals with progressive disclosure (accordions). The user never leaves the main table, friction disappears and deployment time is reduced to zero.",
      retro_card1: "Technical restrictions enhance creativity.",
      retro_card2: "Standardizing the basics reduces 80% of the cognitive load.",
      retro_card3: "Design is useless if you don't speak the development language.",
      retro_badge: "Retrospective",
      retro_title_1: "Think like an Engineer,",
      retro_title_2: "Design for Humans",
      retro_desc: "The biggest challenge was not visual, it was technical. Working with the strict restriction of \"don't touch the code architecture\" forced me to audit Tailwind classes in the browser and reverse engineer them. I learned that a Design System does not need 100 perfect components to provide value; you need 10 atomic components that developers really want and can use without friction.",
      fb_badge: "FEEDBACK",
      fb_title: "Real Impact on the Business",
      fb_desc: "The biggest learning was verifying that technical restrictions enhance creativity. Working with the strict rule of \"don't touch the code architecture\" forced me to do reverse engineering. I discovered that a good Design System doesn't need 100 perfect components; You need the right 10 pieces that restore customer trust and streamline developers' work.",
      fb_quote1: "\"The change was radical. We went from an interface that gave us doubts to a premium product that we are proud to show. Visual order resolved 80% of our friction.\"",
      fb_author1: "Pedro Gonzalez",
      fb_role1: "Stakeholder / End Client",
      fb_quote2: "\"MVP's rescue was a total success. The ability to sort out the chaos by standardizing components without making us rewrite the front-end saved us months of development.\"",
      fb_author2: "Brenda Rangel",
      fb_role2: "CEO, Nuxio",
      ac_badge: "ATOMIC COMPONENTS",
      ac_title: "Hierarchy of Actions and States",
      ac_desc: "Definition of primary and secondary buttons with clear states (default, hover, disabled) to avoid operational errors. We prioritize visual contrast and semiotic semantics to guide the user, ensuring that complementary actions never visually compete with the main 'Happy Path'.",
      ac_tag1: "2 variants",
      ac_tag2: "3 states",
      ac_tag3: "10px radius",
      ac_color_label: "Color tokens",
      gh_badge: "GOVERNANCE & HANDOFF",
      gh_title: "GOVERNANCE & HANDOFF",
      gh_desc: "To avoid discrepancies between Figma and production, we implemented Storybook as our single source of truth. This allowed us to isolate the development environment, test React components in all their states, and provide live documentation of Tailwind classes for the engineering team.",
      gh_bullet1: "Components isolated from the global context",
      gh_bullet2: "Visual testing of all states",
      gh_bullet3: "Live documentation exportable to the computer",
      gh_tech1: "Storybook 7.x",
      gh_tech2: "React 18",
      gh_tech3: "Tailwind CSS",
      gh_tech4: "Figma Plugin"
    }
  },
  es: {
    nav: {
      products: "Proyectos Clave",
      methodology: "Metodología",
      experience: "Experiencia",
      education: "Educación",
      about: "Sobre Mí",
      cv: "Descargar CV"
    },
    hero: {
      badge: "Diseñador de Producto Senior & UX Engineer",
      title1: "Diseño de producto",
      title2: "impulsado por la ingeniería",
      scramble: "rigor.",
      link1: "Proyectos",
      link2: "Metodología"
    },
    products: {
      badge: "01 — Productos de Impacto",
      title: "Trabajo Destacado",
      subtitle: "Proyectos donde la arquitectura de diseño y la calidad del código se interceptan para resolver problemas reales de negocio.",
      nuxio_cat: "B2B Industrial",
      nuxio_desc: "Un panel crítico para la respuesta a emergencias industriales. Flujos de datos complejos simplificados en una interfaz procesable y de alto contraste para entornos de alta tensión.",
      electro_cat: "E-Commerce",
      electro_desc: "Un frontend de alta conversión construido con React y Firebase. Enfocado en micro-interacciones y un proceso de pago sin fricciones.",
      figma_cat: "Herramientas de IA",
      figma_desc: "Librería de componentes y prompts de layout estrictos diseñados para la generación de interfaces con IA dentro del ecosistema de Material Design 3.",
      agentic_cat: "SAAS B2B DE IA",
      agentic_desc: "Diseñé una plataforma SaaS B2B completa para una IA desde cero, enfocada en escalabilidad, densidad de datos y experiencia de usuario.",
      lab_cat: "COMPONENTES REACT",
      lab_desc: "Una colección curada de nuestros destacados: componentes UI diseñados con precisión milimétrica y traducidos a código React limpio en varios proyectos.",
      link: "Ver Caso de Estudio",
      lab_link_text: "Ver Librería"
    },
    laboratory: {
      badge: "Patio de Ingeniería",
      title: "El Laboratorio Desktop.",
      desc: "Una exhibición de 16 interacciones React de alta fidelidad centradas en entornos de escritorio SaaS B2B. Prueba la paleta Cmd+K, los inputs de etiquetas y la tarjeta en perspectiva.",
      cmdk_search: "Buscar incidencias...",
      cmdk_placeholder: "Escribe un comando...",
      cmdk_esc: "ESC",
      cmdk_suggestions: "Sugerencias",
      cmdk_assign: "Asignar a mí",
      cmdk_status: "Cambiar Estado",
      status_backlog: "Backlog",
      status_todo: "Por hacer",
      status_in_progress: "En progreso",
      status_done: "Completado",
      perspective_tilt: "INCLÍNAME",
      kanban_item1: "Investigación UX",
      kanban_item2: "Integración API",
      kanban_item3: "Pulido UI",
      kanban_drag: "Arrastra para reordenar",
      tags_placeholder: "Escribe y presiona enter...",
      tags_hint: "Presiona Enter para agregar",
      otp_trigger: "Forzar Error",
      skeleton_tap: "Toca para alternar",
      search_placeholder: "Buscar...",
      hold_deleted: "Eliminado",
      hold_delete: "Mantén para Borrar",
      swipe_lock: "Desliza para Abrir",
      pwd_placeholder: "Ingresa la contraseña",
      deploy_btn: "Desplegar",
      c1_title: "Paleta de Comandos", c1_tag: "Patrón UX",
      c2_title: "Selector de Estado", c2_tag: "UI Escritorio",
      c3_title: "Perspectiva 3D", c3_tag: "Físicas de Mouse",
      c4_title: "Reordenamiento Kanban", c4_tag: "Espacio de Trabajo",
      c5_title: "Pestañas Animadas", c5_tag: "Layout",
      c6_title: "Mantener para Borrar", c6_tag: "UX de Seguridad",
      c7_title: "OTP con Auto-Foco", c7_tag: "Seguridad",
      c8_title: "Input Multi-Etiquetas", c8_tag: "Formularios",
      c9_title: "Búsqueda Expansible", c9_tag: "Navegación UI",
      c10_title: "Fuerza de Contraseña", c10_tag: "Formularios",
      c11_title: "Morphing de Esqueleto", c11_tag: "Estado de Carga",
      c12_title: "Visualizador de Voz", c12_tag: "Animación IA",
      c13_title: "Deslizar para Desbloquear", c13_tag: "UX Móvil",
      c14_title: "Reacción de Me Gusta", c14_tag: "UI de Feedback",
      c15_title: "Volumen de Hardware", c15_tag: "Inputs",
      c16_title: "Carga de Submit", c16_tag: "Botones"
    },
    methodology: {
      badge: "03 — Metodología",
      title: "El Método Basado en Lógica",
      m1_title: "Arquitectura de la Información",
      m1_desc: "Diseño de estructuras que soportan el crecimiento del software, no solo pantallas aisladas. Cada jerarquía es intencional, cada flujo es validado antes de mover un píxel.",
      m2_title: "Viabilidad Técnica",
      m2_desc: "Tener formación en ingeniería elimina el retrabajo. Diseño dentro de restricciones reales: interfaces implementables que los desarrolladores pueden construir con confianza.",
      m3_title: "Prototipado Inteligente",
      m3_desc: "Las herramientas modernas (React, IA) validan las experiencias en entornos similares a producción antes de escribir una sola línea de código."
    },
    experience: {
      badge: "04 — Carrera",
      title: "Experiencia Laboral",
      exp1_period: "2024 — Presente",
      exp1_company: "Independiente",
      exp1_role: "Diseñador de Producto Freelance",
      exp1_desc: "Enfoque en productos impulsados por IA y Optimización de la Tasa de Conversión. Colaborando con startups y marcas establecidas para lanzar soluciones de diseño impactantes.",
      exp2_period: "2025 — 2026",
      exp2_company: "Nuxio Software",
      exp2_role: "UX Lead",
      exp2_desc: "Liderazgo de equipos y plataformas industriales críticas. Lideré la estrategia de diseño para productos B2B complejos, guiando a diseñadores junior y estableciendo sistemas de diseño.",
      exp3_period: "En Progreso",
      exp3_company: "Universidad Nacional de Hurlingham",
      exp3_role: "Ingeniería Informática",
      exp3_desc: "Construyendo una base algorítmica. Cerrando la brecha entre la intuición del diseño y la precisión de la ingeniería a través de la educación formal en ciencias de la computación."
    },
    education: {
      badge: "05 — Educación",
      title: "Educación",
      cert_btn: "Ver Certificación",
      front_title: "Certificación en Desarrollo Frontend",
      front_desc: "Programa intensivo centrado en la construcción de aplicaciones web escalables y de alto rendimiento utilizando ecosistemas modernos de React y técnicas de optimización.",
      front_inst: "CoderHouse",
      ux_title: "Certificación en Diseño UX/UI",
      ux_desc: "Formación integral en diseño centrado en el usuario, estrategia de producto y sistemas de diseño para interfaces digitales complejas.",
      ux_inst: "CoderHouse",
      eng_title: "Ingeniería Informática",
      eng_desc: "Construyendo una base algorítmica. Cerrando la brecha entre la intuición del diseño y la precisión de la ingeniería a través de la educación formal en ciencias de la computación.",
      eng_inst: "Universidad Nacional de Hurlingham",
      eng_year: "2022 - En Progreso"
    },
    about: {
      badge: "06 — Sobre Mí",
      title: "El Diseñador Detrás del Trabajo",
      p1: "Vinculo la consistencia del diseño con la lógica. Como Diseñador de Producto Senior y ex UX Lead, abordo cada proyecto con la creencia de que un diseño verdaderamente excelente no solo es hermoso: es funcional, escalable y técnicamente sólido.",
      p2: "Mi formación en ingeniería me da una perspectiva única. No me limito a entregar mockups: entiendo las limitaciones y posibilidades del código.",
      p3_start: "Más allá del trabajo con clientes, lidero una creciente comunidad de diseño de ",
      p3_highlight: "más de 12.000 profesionales",
      p3_end: "."
    },
    contact: {
      badge: "Ponte en contacto",
      title: "Hablemos de tu próximo producto.",
      desc: "Disponible para proyectos freelance seleccionados y oportunidades a tiempo completo. Contáctame para discutir cómo el rigor en diseño e ingeniería puede acelerar tu producto.",
      btn: "Enviar Email",
      subtext: "hello@alan.design · Usualmente responde en 24h",
      motto: "Belleza funcional, siempre.",
      resume: "Currículum"
    },
    agentic: {
      hero_title: "Agentic OS:",
      hero_subtitle: "De 0 a 1 en el ecosistema de IA",
      hero_desc: "Diseño de un MVP escalable y UI Kit para una plataforma B2D (Business to Developer) orientada a la gestión de Agentes de Inteligencia Artificial.",
      tag_role: "Diseñador de Producto Principal",
      tag_duration: "8 semanas",
      tag_type: "Proyecto 0 a 1",
      tag_platform: "Web App / SaaS B2B",
      context_badge: "02 — CONTEXTO",
      context_title: "El Desafío y la Solución",
      problem_tag: "EL PROBLEMA",
      problem_title: "Densidad Cognitiva vs. Eficiencia",
      problem_desc: "Diseñar para ingenieros de IA requiere precisión absoluta. El desafío fue manejar un volumen masivo de datos crudos (consumo de tokens, logs en tiempo real, latencia y costos de múltiples LLMs) sin generar fatiga visual. Las herramientas técnicas tradicionales suelen sacrificar usabilidad por funcionalidad, resultando en interfaces abrumadoras.",
      solution_tag: "LA SOLUCIÓN",
      solution_title: "Ecosistema Modular y Nativo",
      solution_desc: "Desarrollamos un MVP respaldado por un UI Kit atómico y un Modo Oscuro profundo, diseñado para reducir el brillo y la fatiga visual. Priorizamos el contraste tipográfico y la jerarquía en las tablas de datos, permitiendo al equipo de ingeniería iterar y escalar nuevas funcionalidades rápidamente sin romper la coherencia visual.",
      atomic_badge: "03 — DISEÑO ATÓMICO",
      atomic_title: "Escalabilidad desde la base",
      atomic_desc: "Componentes modulares diseñados con precisión milimétrica.",
      atomic_b1_tag: "ÁTOMOS / INTERACCIÓN",
      atomic_b1_title: "Prevención de Errores\ny Accesibilidad",
      atomic_b1_desc: "En herramientas para desarrolladores, la velocidad de escritura es clave. Diseñamos Focus Rings en cyan de alto contraste y estados de error en rojo vibrante para dar feedback inmediato sin textos largos, cumpliendo con estándares WCAG en Modo Oscuro.",
      atomic_b2_tag: "ORGANISMOS / DATOS",
      atomic_b2_title: "Escaneabilidad\nen Alta Densidad",
      atomic_b2_desc: "Redujimos la carga cognitiva eliminando líneas divisorias verticales y usando padding generoso. Implementamos tipografía monoespaciada para alinear métricas financieras y estados, permitiendo al usuario escanear logs complejos en segundos.",
      atomic_b3_tag: "CONVERSIÓN Y DASHBOARD",
      atomic_b3_title: "Jerarquía Visual\nOrientada a Negocio",
      atomic_b3_desc: "Aislamos datos críticos en tarjetas de lectura rápida. Para la conversión (Precios), invertimos el peso visual: redujimos el ruido secundario y dimos prominencia tipográfica al precio y al CTA, asegurando un flujo de upgrade sin distracciones.",
      workflow_badge: "04 — FLUJO DE TRABAJO",
      workflow_title: "De Figma a Storybook",
      core_badge: "05 — Flujos Core",
      core_title: "Agentic OS: La Experiencia Core",
      core_desc: "Visualizamos la plataforma completa, orquestando datos de alta densidad y el control de agentes en un dashboard unificado y eficiente.",
      outcomes_badge: "06 — RESULTADOS E IMPACTO",
      outcomes_title: "Resultados y Validación del Equipo",
      metric1_title: "Aceleración del Handoff",
      metric1_desc: "Reducción del tiempo de programación al automatizar componentes base.",
      metric2_title: "Consistencia Visual",
      metric2_desc: "Garantía de fidelidad total entre el diseño atómico en Figma y la implementación final en Storybook.",
      testimonial_quote: "Alan tiene una visión técnica que rara vez se ve en UX. Su flujo de handoff con IA nos ahorró semanas de maquetado. Las pantallas llegan listas para integrar.",
      testimonial_role: "Líder Técnico Frontend",
      testimonial_company: "@ Agnetic",
      next_steps_badge: "PRÓXIMOS PASOS →",
      next_steps_desc: "Construyendo en público y compartiendo el flujo de trabajo técnico con la comunidad: documentando el proceso de diseño modular, trucos de maquetación e integración de IA en formatos cortos para diseñadores y desarrolladores."
    },
    nuxio: {
      hero_title_1: "Rescate, Estandarización y",
      hero_title_2: "Evolución SaaS B2B.",
      hero_desc_1: "PrintFlow Pro es un software integral de gestión y logística para cadenas de imprentas, desarrollado internamente en Nuxio.",
      hero_desc_2: "Como UX/UI Lead, ejecuté un rediseño crítico de emergencia para salvar un MVP al borde de ser rechazado. Mediante ingeniería inversa y creando un Sistema de Diseño adaptado a Tailwind, transformamos un diseño ineficiente en un producto premium sin descartar el código frontend en producción.",
      kpi_1_value: "14",
      kpi_1_unit: "Días",
      kpi_1_label: "Rediseño\nCrítico",
      kpi_2_value: "100%",
      kpi_2_label: "Aprobación\ndel Cliente",
      kpi_3_value_1: "0",
      kpi_3_value_2: "1",
      kpi_3_label: "Sistema de Diseño\nCreado",
      banner_role_label: "ROL",
      banner_role_val: "UX/UI Lead",
      banner_platform_label: "PLATAFORMA",
      banner_platform_val: "Web App / SaaS B2B",
      banner_stack_label: "STACK Y HERRAMIENTAS",
      banner_stack_val: "Figma / React",
      banner_time_label: "TIEMPO CRÍTICO",
      banner_time_val: "14 Días (Rescate)",
      principles_title: "Principios de Diseño",
      p1_title: "Cero Reescritura (Sinergia Técnica)",
      p1_desc: "Diseñar pensando estrictamente en las limitaciones del código existente y el stack de React + Tailwind.",
      p2_title: "Carga Cognitiva Reducida",
      p2_desc: "Simplificar la densidad de datos para operadores que usan la plataforma 8 horas al día.",
      p3_title: "Prevención de Errores",
      p3_desc: "Ocultar acciones destructivas y crear flujos operativos a prueba de fallos.",
      p4_title: "Escalabilidad Modular",
      p4_desc: "Pensar en componentes atómicos para que las futuras pantallas se armen como piezas de Lego.",
      ts_badge: "Planificación del Proyecto",
      ts_title: "Sprints y Cronograma",
      ts_s1_name: "SPRINT 1",
      ts_s1_week: "SEMANA 1",
      ts_s1_title: "Auditoría y Triage",
      ts_s1_desc: "Diagnóstico y estabilización",
      ts_s2_name: "SPRINT 2",
      ts_s2_week: "SEMANA 2",
      ts_s2_title: "Estandarización",
      ts_s2_desc: "Tailwind sin reescribir",
      ts_s3_name: "SPRINT 3",
      ts_s3_week: "SEMANA 3-4",
      ts_s3_title: "Re-arquitectura",
      ts_s3_desc: "De páginas a modales",
      ts_s4_name: "SPRINT 4",
      ts_s4_week: "SEMANA 5-6",
      ts_s4_title: "Handoff y QA",
      ts_s4_desc: "Documentación en Storybook",
      ts_legend1: "Auditoría UI y Rescate",
      ts_legend2: "Estandarización y MVP",
      ts_legend3: "Re-arquitectura de Flujos UX",
      ts_legend4: "Handoff y QA Técnico",
      dops_badge: "OPERACIONES DE DISEÑO",
      dops_title: "Ingeniería Inversa y Sistema Atómico",
      dops_desc: "Estandarización de componentes interactivos mapeados directamente a clases de Tailwind CSS. Eliminamos los saltos de layout unificando bordes a 1px y mejoramos la accesibilidad de los estados de error siguiendo normas WCAG, todo sin reescribir el código base.",
      dops_stat1_val: "48+",
      dops_stat1_label: "Componentes",
      dops_stat2_val: "120+",
      dops_stat2_label: "Tokens",
      dops_stat3_val: "AA",
      dops_stat3_label: "Nivel WCAG",
      cc_title: "Reducción de Complejidad Cognitiva",
      cc_desc: "Transformamos un flujo de trabajo pesado y propenso a errores en una experiencia modular. Priorizamos la retención del contexto visual del usuario, respetando estrictamente la restricción técnica de no reescribir el Front-end.",
      cc_step1_title: "01 / El Problema",
      cc_step1_desc: "El usuario perdía el contexto al ser redirigido a una nueva página para editar datos. El muro de inputs causaba fatiga visual y el botón de acción destructiva expuesto era un riesgo crítico.",
      cc_step2_title: "02 / Wireframes",
      cc_step2_desc: "Descartamos limpiar toda la página, ya que reescribir ese código violaba nuestro límite de 14 días. Bocetamos un esqueleto basado en overlays para reutilizar componentes existentes.",
      cc_step3_title: "03 / La Solución",
      cc_step3_desc: "Migramos la edición a modales contextuales con revelación progresiva (acordeones). El usuario nunca abandona la tabla principal, la fricción desaparece y el tiempo de implementación se reduce a cero.",
      retro_card1: "Las restricciones técnicas potencian la creatividad.",
      retro_card2: "Estandarizar lo básico reduce el 80% de la carga cognitiva.",
      retro_card3: "El diseño es inútil si no hablas el lenguaje de desarrollo.",
      retro_badge: "Retrospectiva",
      retro_title_1: "Piensa como Ingeniero,",
      retro_title_2: "Diseña para Humanos",
      retro_desc: "El mayor desafío no fue visual, fue técnico. Trabajar con la estricta restricción de \"no tocar la arquitectura del código\" me obligó a auditar clases de Tailwind en el navegador y hacer ingeniería inversa. Aprendí que un Sistema de Diseño no necesita 100 componentes perfectos para aportar valor; necesitas 10 componentes atómicos que los desarrolladores realmente quieran y puedan usar sin fricción.",
      fb_badge: "FEEDBACK",
      fb_title: "Impacto Real en el Negocio",
      fb_desc: "El mayor aprendizaje fue comprobar que las restricciones técnicas potencian la creatividad. Trabajar con la regla estricta de \"no tocar la arquitectura del código\" me obligó a hacer ingeniería inversa. Descubrí que un buen Sistema de Diseño no necesita 100 componentes perfectos; necesitas las 10 piezas correctas que restauran la confianza del cliente y agilizan el trabajo de los desarrolladores.",
      fb_quote1: "\"El cambio fue radical. Pasamos de una interfaz que nos generaba dudas a un producto premium que nos enorgullece mostrar. El orden visual resolvió el 80% de nuestra fricción.\"",
      fb_author1: "Pedro Gonzalez",
      fb_role1: "Stakeholder / Cliente Final",
      fb_quote2: "\"El rescate del MVP fue un éxito total. La capacidad de ordenar el caos estandarizando componentes sin hacernos reescribir el front-end nos ahorró meses de desarrollo.\"",
      fb_author2: "Brenda Rangel",
      fb_role2: "CEO, Nuxio",
      ac_badge: "COMPONENTES ATÓMICOS",
      ac_title: "Jerarquía de Acciones y Estados",
      ac_desc: "Definición de botones primarios y secundarios con estados claros (default, hover, disabled) para evitar errores operativos. Priorizamos el contraste visual y la semántica para guiar al usuario, asegurando que las acciones secundarias no compitan con el 'Happy Path'.",
      ac_tag1: "2 variantes",
      ac_tag2: "3 estados",
      ac_tag3: "10px radius",
      ac_color_label: "Tokens de color",
      gh_badge: "GOBERNANZA Y HANDOFF",
      gh_title: "GOBERNANZA Y HANDOFF",
      gh_desc: "Para evitar discrepancias entre Figma y producción, implementamos Storybook como única fuente de verdad. Esto nos permitió aislar el entorno de desarrollo, probar componentes React en todos sus estados y proveer documentación viva de las clases de Tailwind al equipo de ingeniería.",
      gh_bullet1: "Componentes aislados del contexto global",
      gh_bullet2: "Testing visual de todos los estados",
      gh_bullet3: "Documentación viva exportable al equipo",
      gh_tech1: "Storybook 7.x",
      gh_tech2: "React 18",
      gh_tech3: "Tailwind CSS",
      gh_tech4: "Plugin de Figma"
    }
  }
};

type Translations = typeof translations.en;

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (section: keyof Translations, key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === 'en' ? 'es' : 'en'));
  };

  const t = (section: keyof Translations, key: string): string => {
    return (translations[language][section] as any)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
}